name: Django CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-python@v2
      with:
        python-version: 3.x 

    - name: Build Docker image
      run: |
        docker build -t test .  
        docker run test python manage.py test 
